# Generated by Django 5.1.7 on 2025-03-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='caregiver_group',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('physician', 'Physician'), ('imaging', 'Imaging'), ('nutrition', 'Nutrition'), ('rehab', 'Rehab'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
