"""
Django settings for triage_app project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s#bq!s4)$3kh60u##_&sr48zi^8ng-8vr)#oen!in72=nj554s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mortality_prediction',
    'data_entry',
    'accounts',
    'django_select2',
]

# Select2 settings
SELECT2_CACHE_BACKEND = 'default'
SELECT2_CSS = 'django_select2/dist/css/select2.min.css'
SELECT2_JS = 'django_select2/dist/js/select2.min.js'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'triage_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # This is important
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'triage_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add this setting to tell Django where to look for static files in development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ML Inference
ML_MODEL_DIR = os.path.join(BASE_DIR, 'ml', 'models')

# ML_MODEL_TYPE = 'xgboost'
ML_MODEL_TYPE = 'neural'

# EMBEDDING_TYPE = 'clinicalBERT-unchunked'
EMBEDDING_TYPE = 'clinicalBERT-chunked'
# EMBEDDING_TYPE = 'biomedLM-chunked'

ONE_HOT_ENCODER_PATH = os.path.join(ML_MODEL_DIR, 'one_hot_encoder1.joblib')

XGBOOST_DIR = os.path.join(ML_MODEL_DIR, EMBEDDING_TYPE, 'xgboost')
XGBOOST_MODEL_PATH = os.path.join(XGBOOST_DIR, 'xgboost2_pca99.joblib')
XGBOOST_PCA_PATH = os.path.join(XGBOOST_DIR, 'pca_objects99.joblib')

NEURAL_DIR = os.path.join(ML_MODEL_DIR, EMBEDDING_TYPE, 'neural_classifier')
NEURAL_MODEL_PATH = os.path.join(NEURAL_DIR, 'hd256_medium_lr0.01_bs8192_dr0.5_ep100_bce_sp3_es10_mpFalse_pca0.99.pth')
NEURAL_PCA_DICT_PATH = os.path.join(NEURAL_DIR, 'pca_objects99.joblib')
NEURAL_HIDDEN_DIM = 256
NEURAL_MODEL_TYPE = 'medium'
NEURAL_DROPOUT = 0.5

EMBEDDING_COLS = ['note_embedding', 'prescription_embedding']