# Generated by Django 5.1.7 on 2025-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('dod', models.DateField(blank=True)),
                ('ethnicity', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('hispanic', 'Hispanic'), ('asian', 'Asian'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_dt', models.DateTimeField()),
                ('admission_location', models.CharField(choices=[('er', 'ER'), ('phys_ref', 'Physician Referral'), ('clinic_ref', 'Clinic Referral'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=10)),
                ('insurance_type', models.CharField(choices=[('private', 'Private'), ('medicare', 'Medicare'), ('medicaid', 'Medicaid'), ('self_pay', 'Self Pay'), ('government', 'Government')], default='self_pay', max_length=10)),
                ('caregiver', models.ManyToManyField(to='accounts.caregiver')),
                ('patient_id', models.ManyToManyField(to='data_entry.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_dt', models.DateTimeField()),
                ('note_text', models.TextField()),
                ('admission_id', models.ManyToManyField(to='data_entry.admission')),
                ('caregiver', models.ManyToManyField(to='accounts.caregiver')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('rx_id', models.AutoField(primary_key=True, serialize=False)),
                ('rx_start_date', models.DateField()),
                ('rx_end_date', models.DateField(blank=True)),
                ('rx_name', models.CharField(max_length=100)),
                ('rx_dose', models.CharField(max_length=20)),
                ('admission_id', models.ManyToManyField(to='data_entry.admission')),
                ('patient_id', models.ManyToManyField(to='data_entry.patient')),
            ],
        ),
    ]
