# Generated by Django 5.1.7 on 2025-03-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_caregiver_caregiver_group'),
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='noteevent',
            name='admission_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='admission_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='data_entry.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noteevent',
            name='admission',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='data_entry.admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='admission',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='data_entry.admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='data_entry.patient'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='admission',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='noteevent',
            name='caregiver',
        ),
        migrations.AlterField(
            model_name='patient',
            name='dod',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='caregiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='accounts.caregiver'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='caregiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='accounts.caregiver'),
        ),
    ]
