# Generated by Django 5.1.7 on 2025-03-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0002_remove_admission_patient_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default="John", max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default="Doe", max_length=50),
        ),
    ]
