# Generated by Django 5.1.7 on 2025-04-03 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0003_patient_first_name_patient_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteevent",
            name="patient",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="data_entry.patient",
            ),
            preserve_default=False,
        ),
    ]
