# Generated by Django 5.1.7 on 2025-04-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_caregiver_caregiver_group"),
        ("data_entry", "0004_noteevent_patient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoteEvent",
            new_name="Note",
        ),
    ]
