# Generated by Django 5.1.7 on 2025-04-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0005_rename_noteevent_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="insurance_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("medicare", "Medicare"),
                    ("medicaid", "Medicaid"),
                    ("self_pay", "Self Pay"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                default="self_pay",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="rx_dose",
            field=models.CharField(max_length=100),
        ),
    ]
